#!/usr/bin/env python
"""
This is a small script that does the equivalent of multicrab.
"""
import os
from optparse import OptionParser

from CRABAPI.RawCommand import crabCommand
from CRABClient.ClientExceptions import ClientException
from httplib import HTTPException


def getOptions():
    """
    Parse and return the arguments provided by the user.
    """
    usage = ("Usage: %prog --crabCmd CMD [--workArea WAD --crabCmdOpts OPTS]"
             "\nThe multicrab command executes 'crab CMD OPTS' for each project directory contained in WAD"
             "\nUse multicrab -h for help")

    parser = OptionParser(usage=usage)

    parser.add_option('-c', '--crabCmd',
                      dest = 'crabCmd',
                      default = '',
                      help = "crab command",
                      metavar = 'CMD')

    parser.add_option('-w', '--workArea',
                      dest = 'workArea',
                      default = '',
                      help = "work area directory (only if CMD != 'submit')",
                      metavar = 'WAD')

    parser.add_option('-o', '--crabCmdOpts',
                      dest = 'crabCmdOpts',
                      default = '',
                      help = "options for crab command CMD",
                      metavar = 'OPTS')

    (options, arguments) = parser.parse_args()

    if arguments:
        parser.error("Found positional argument(s): %s." % (arguments))
    if not options.crabCmd:
        parser.error("(-c CMD, --crabCmd=CMD) option not provided.")
    if options.crabCmd != 'submit':
        if not options.workArea:
            parser.error("(-w WAR, --workArea=WAR) option not provided.")
        if not os.path.isdir(options.workArea):
            parser.error("'%s' is not a valid directory." % (options.workArea))

    return options


def main():
    #################################
    #reduced     = True
    reduced     = False
    era         = '2017'
    isLocal     = 'False'
    isData      = 'True'

    if isData == 'False':
	sampleType  = 'mc'
	doHLTFilter = 'False'
    else:
	sampleType  = 'data'
	doHLTFilter = 'True'

    ##################################
    options = getOptions()

    # The submit command needs special treatment.
    if options.crabCmd == 'submit':

        #--------------------------------------------------------
        # This is the base config:
        #--------------------------------------------------------
        from CRABClient.UserUtilities import config, getUsernameFromSiteDB
        config = config()

        config.General.requestName     = None
        #config.General.workArea        = era+'_'+sampleType+'_legacy'
        config.General.workArea        = era+'_'+sampleType+'_legacy_trigBits_resubmit'
        config.General.transferOutputs = True
        config.General.transferLogs    = False

        config.JobType.pluginName = 'Analysis'
	if reduced:
	        config.JobType.psetName = 'makingBacon_25ns_MINIAOD_REDUCED.py'
	else:
	        config.JobType.psetName = 'makingBacon_25ns_MINIAOD.py'
		
        #config.JobType.pyCfgParams = ['isData=False', 'doHLTFilter=False', 'era=2016','isLocal=False']
        config.JobType.pyCfgParams = ['isData='+isData, 'doHLTFilter='+doHLTFilter, 'era='+era,'isLocal='+isLocal]
        config.JobType.outputFiles = ['Output.root']

        config.Data.inputDataset = None
        config.Data.inputDBS = 'global'
        config.Data.ignoreLocality = True
        config.section_("Debug")
        config.Debug.extraJDL = ['+CMS_ALLOW_OVERFLOW=False']
        config.Site.whitelist = ["T2_US*"]
        #config.Site.blacklist = ["T2_US_UCSD"]
        config.Data.splitting = 'EventAwareLumiBased'
        #config.Data.splitting = 'LumiBased'
        #config.Data.splitting = 'FileBased'
	#config.Data.runRange = ''

	#config.Data.lumiMask  = ''
	#config.Data.lumiMask  = '2017_data_legacy_trigBits/crab_DoubleMuon_Run2017E-31Mar2018-v1/results/notFinishedLumis.json'
	#config.Data.lumiMask  = '2017_data_legacy_trigBits/crab_DoubleMuon_Run2017F-31Mar2018-v1/results/notFinishedLumis.json'
	#config.Data.lumiMask  = '2017_data_legacy_trigBits/crab_DoubleEG_Run2017F-31Mar2018-v1/results/notFinishedLumis.json'
	config.Data.lumiMask  = '2017_data_legacy_trigBits/crab_DoubleEG_Run2017B-31Mar2018-v1/results/notFinishedLumis.json'

	#config.Data.unitsPerJob = 1

	config.Data.unitsPerJob = 20000

	#config.Data.totalUnits = 500000
        #config.Data.totalUnits = 3

        config.Data.outputDatasetTag = None
        #config.Data.outLFNDirBase = '/store/user/%s/'% (getUsernameFromSiteDB()) + sampleType+'_legacy_gen_'+era+'/' 
        #config.Data.outLFNDirBase = '/store/group/lpcbacon/corderom/'+ sampleType+'_'+era+'/' 
        config.Data.outLFNDirBase = '/store/group/lpchzg/corderom/'+ sampleType+'_'+era+'/' 

        config.Site.storageSite = 'T3_US_FNALLPC' # Choose your site. 
        #--------------------------------------------------------

        # Will submit one task for each of these input datasets.
        inputDatasets = [

                            #'/SingleMuon/Run2016B-03Feb2017_ver2-v2/MINIAOD', 
                            #'/SingleMuon/Run2016C-03Feb2017-v1/MINIAOD',
                            #'/SingleMuon/Run2016D-03Feb2017-v1/MINIAOD',
                            #'/SingleMuon/Run2016E-03Feb2017-v1/MINIAOD',
                            #'/SingleMuon/Run2016F-03Feb2017-v1/MINIAOD',
                            #'/SingleMuon/Run2016G-03Feb2017-v1/MINIAOD',
                            #'/SingleMuon/Run2016H-03Feb2017_ver2-v1/MINIAOD',
                            #'/SingleMuon/Run2016H-03Feb2017_ver3-v1/MINIAOD',

                            #'/DoubleMuon/Run2016B-03Feb2017_ver2-v2/MINIAOD',
                            #'/DoubleMuon/Run2016C-03Feb2017-v1/MINIAOD',
                            #'/DoubleMuon/Run2016D-03Feb2017-v1/MINIAOD',
                            #'/DoubleMuon/Run2016E-03Feb2017-v1/MINIAOD',
                            #'/DoubleMuon/Run2016F-03Feb2017-v1/MINIAOD',
                            #'/DoubleMuon/Run2016G-03Feb2017-v1/MINIAOD',
                            #'/DoubleMuon/Run2016H-03Feb2017_ver2-v1/MINIAOD',
                            #'/DoubleMuon/Run2016H-03Feb2017_ver3-v1/MINIAOD',
                           
                            #'/DoubleEG/Run2016B-03Feb2017_ver2-v2/MINIAOD',
                            #'/DoubleEG/Run2016C-03Feb2017-v1/MINIAOD',
                            #'/DoubleEG/Run2016D-03Feb2017-v1/MINIAOD',
                            #'/DoubleEG/Run2016E-03Feb2017-v1/MINIAOD',
                            #'/DoubleEG/Run2016F-03Feb2017-v1/MINIAOD',
                            #'/DoubleEG/Run2016G-03Feb2017-v1/MINIAOD',
                            #'/DoubleEG/Run2016H-03Feb2017_ver2-v1/MINIAOD',
                            #'/DoubleEG/Run2016H-03Feb2017_ver3-v1/MINIAOD',

                            #'/MuOnia/Run2016B-03Feb2017_ver2-v2/MINIAOD',
                            #'/MuOnia/Run2016C-03Feb2017-v1/MINIAOD',
                            #'/MuOnia/Run2016D-03Feb2017-v1/MINIAOD',
                            #'/MuOnia/Run2016E-03Feb2017-v1/MINIAOD',
                            #'/MuOnia/Run2016F-03Feb2017-v1/MINIAOD',
                            #'/MuOnia/Run2016G-03Feb2017-v1/MINIAOD',
                            #'/MuOnia/Run2016H-03Feb2017_ver2-v1/MINIAOD',
                            #'/MuOnia/Run2016H-03Feb2017_ver3-v1/MINIAOD',
                            
                            #'/Charmonium/Run2016B-03Feb2017_ver2-v2/MINIAOD',
                            #'/Charmonium/Run2016C-03Feb2017-v1/MINIAOD',
                            #'/Charmonium/Run2016D-03Feb2017-v1/MINIAOD',
                            #'/Charmonium/Run2016E-03Feb2017-v1/MINIAOD',
                            #'/Charmonium/Run2016F-03Feb2017-v1/MINIAOD',
                            #'/Charmonium/Run2016G-03Feb2017-v1/MINIAOD',
                            #'/Charmonium/Run2016H-03Feb2017_ver2-v1/MINIAOD',
                            #'/Charmonium/Run2016H-03Feb2017_ver3-v1/MINIAOD',

			    ######################################
			    ##########  2016 LEGACY  #############

			    ##------------------- Double Muon --------------
			    #'/DoubleMuon/Run2016B-17Jul2018_ver1-v1/MINIAOD',
			    #'/DoubleMuon/Run2016B-17Jul2018_ver2-v1/MINIAOD',
			    #'/DoubleMuon/Run2016C-17Jul2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2016D-17Jul2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2016E-17Jul2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2016F-17Jul2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2016G-17Jul2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2016H-17Jul2018-v1/MINIAOD',
       
			    ##------------------ DoubleEG ------------------
			    #'/DoubleEG/Run2016B-17Jul2018_ver1-v1/MINIAOD',
			    #'/DoubleEG/Run2016B-17Jul2018_ver2-v1/MINIAOD',
			    #'/DoubleEG/Run2016C-17Jul2018-v1/MINIAOD',
			    #'/DoubleEG/Run2016D-17Jul2018-v1/MINIAOD',
			    #'/DoubleEG/Run2016E-17Jul2018-v1/MINIAOD',
			    #'/DoubleEG/Run2016F-17Jul2018-v1/MINIAOD',
			    #'/DoubleEG/Run2016G-17Jul2018-v1/MINIAOD',
			    #'/DoubleEG/Run2016H-17Jul2018-v1/MINIAOD',

			    ######################################
			    ##########  2017 ReReco  #############

			    ##------------------- Double Muon --------------
			    #'/DoubleMuon/Run2017B-31Mar2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2017C-31Mar2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2017D-31Mar2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2017E-31Mar2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2017F-31Mar2018-v1/MINIAOD',
 
			    ##------------------ DoubleEG ------------------
			    '/DoubleEG/Run2017B-31Mar2018-v1/MINIAOD',
			    #'/DoubleEG/Run2017C-31Mar2018-v1/MINIAOD',
			    #'/DoubleEG/Run2017D-31Mar2018-v1/MINIAOD',
			    #'/DoubleEG/Run2017E-31Mar2018-v1/MINIAOD',
			    #'/DoubleEG/Run2017F-31Mar2018-v1/MINIAOD',

			    ###------------------SingleElectron ------------
			    #'/SingleElectron/Run2017B-31Mar2018-v1/MINIAOD',
			    #'/SingleElectron/Run2017C-31Mar2018-v1/MINIAOD',
			    #'/SingleElectron/Run2017D-31Mar2018-v1/MINIAOD',
			    #'/SingleElectron/Run2017E-31Mar2018-v1/MINIAOD',
			    #'/SingleElectron/Run2017F-31Mar2018-v1/MINIAOD',

			    #'/SinglePhoton/Run2017B-31Mar2018-v1/MINIAOD',
			    #'/SinglePhoton/Run2017C-31Mar2018-v1/MINIAOD',
			    #'/SinglePhoton/Run2017D-31Mar2018-v1/MINIAOD',
			    #'/SinglePhoton/Run2017E-31Mar2018-v1/MINIAOD',
			    #'/SinglePhoton/Run2017F-31Mar2018-v1/MINIAOD',

			    ######################################
                            ##########  2018 RECO  #############

                            ##------------------- Double Muon --------------
                            '/DoubleMuon/Run2018A-17Sep2018-v2/MINIAOD',
                            '/DoubleMuon/Run2018B-17Sep2018-v1/MINIAOD',
                            '/DoubleMuon/Run2018C-17Sep2018-v1/MINIAOD',
                            '/DoubleMuon/Run2018D-PromptReco-v2/MINIAOD',

                            ##------------------ DoubleEG ------------------
                            #'/EGamma/Run2018A-17Sep2018-v2/MINIAOD',
                            #'/EGamma/Run2018B-17Sep2018-v1/MINIAOD',
                            #'/EGamma/Run2018C-17Sep2018-v1/MINIAOD',
                            #'/EGamma/Run2018D-22Jan2019-v2/MINIAOD',


 
                        ]

        for inDS in inputDatasets:
            config.General.requestName = inDS.split('/')[1] + '_' + inDS.split('/')[2] 
	    config.General.requestName = config.General.requestName[:99]
            config.Data.inputDataset = inDS
            config.Data.outputDatasetTag = '%s_%s' % (config.General.workArea, config.General.requestName)
            # Submit.
            try:
                print "Submitting for input dataset %s" % (inDS)
                crabCommand(options.crabCmd, config = config, *options.crabCmdOpts.split())
            except HTTPException as hte:
                print "Submission for input dataset %s failed: %s" % (inDS, hte.headers)
            except ClientException as cle:
                print "Submission for input dataset %s failed: %s" % (inDS, cle)

    # All other commands can be simply executed.
    elif options.workArea:

        for dir in os.listdir(options.workArea):
            projDir = os.path.join(options.workArea, dir)
            if not os.path.isdir(projDir):
                continue
            # Execute the crab command.
            msg = "Executing (the equivalent of): crab %s --dir %s %s" % (options.crabCmd, projDir, options.crabCmdOpts)
            print "-"*len(msg)
            print msg
            print "-"*len(msg)
            try:
                crabCommand(options.crabCmd, dir = projDir, *options.crabCmdOpts.split())
            except HTTPException as hte:
                print "Failed executing command %s for task %s: %s" % (options.crabCmd, projDir, hte.headers)
            except ClientException as cle:
                print "Failed executing command %s for task %s: %s" % (options.crabCmd, projDir, cle)


if __name__ == '__main__':
    main()
