#!/usr/bin/env python
"""
This is a small script that does the equivalent of multicrab.
"""
import os
from optparse import OptionParser

from CRABAPI.RawCommand import crabCommand
from CRABClient.ClientExceptions import ClientException
from httplib import HTTPException


def getOptions():
    """
    Parse and return the arguments provided by the user.
    """
    usage = ("Usage: %prog --crabCmd CMD [--workArea WAD --crabCmdOpts OPTS]"
             "\nThe multicrab command executes 'crab CMD OPTS' for each project directory contained in WAD"
             "\nUse multicrab -h for help")

    parser = OptionParser(usage=usage)

    parser.add_option('-c', '--crabCmd',
                      dest = 'crabCmd',
                      default = '',
                      help = "crab command",
                      metavar = 'CMD')

    parser.add_option('-w', '--workArea',
                      dest = 'workArea',
                      default = '',
                      help = "work area directory (only if CMD != 'submit')",
                      metavar = 'WAD')

    parser.add_option('-o', '--crabCmdOpts',
                      dest = 'crabCmdOpts',
                      default = '',
                      help = "options for crab command CMD",
                      metavar = 'OPTS')

    (options, arguments) = parser.parse_args()

    if arguments:
        parser.error("Found positional argument(s): %s." % (arguments))
    if not options.crabCmd:
        parser.error("(-c CMD, --crabCmd=CMD) option not provided.")
    if options.crabCmd != 'submit':
        if not options.workArea:
            parser.error("(-w WAR, --workArea=WAR) option not provided.")
        if not os.path.isdir(options.workArea):
            parser.error("'%s' is not a valid directory." % (options.workArea))

    return options


def main():
    #################################
    era         = '2017'
    doHLTFilter = 'False'
    isData      = 'False'
    isLocal     = 'False'
    if isData == 'False':
	sampleType = 'mc'
    else:
	sampleType = 'data'

    ##################################
    options = getOptions()

    # The submit command needs special treatment.
    if options.crabCmd == 'submit':

        #--------------------------------------------------------
        # This is the base config:
        #--------------------------------------------------------
        from CRABClient.UserUtilities import config, getUsernameFromSiteDB
        config = config()

        config.General.requestName     = None
        #config.General.workArea        = era+'_mc_legacy'
        config.General.workArea        = era+'_'+sampleType+'_legacy'
        config.General.transferOutputs = True
        config.General.transferLogs    = False

        config.JobType.pluginName = 'Analysis'
        #config.JobType.psetName = 'makingBacon_25ns_MINIAOD.py'
        config.JobType.psetName = 'makingBacon_25ns_MINIAOD.py'
        #config.JobType.pyCfgParams = ['isData=False', 'doHLTFilter=False', 'era=2016','isLocal=False']
        config.JobType.pyCfgParams = ['isData='+isData, 'doHLTFilter='+doHLTFilter, 'era='+era,'isLocal='+isLocal]
        config.JobType.outputFiles = ['Output.root']

        config.Data.inputDataset = None
        config.Data.inputDBS = 'global'
        config.Data.ignoreLocality = True
        config.section_("Debug")
        config.Debug.extraJDL = ['+CMS_ALLOW_OVERFLOW=False']
        config.Site.whitelist = ["T2_US*"]
        #config.Site.blacklist = ["T2_US_UCSD"]
        config.Data.splitting = 'EventAwareLumiBased'
        #config.Data.splitting = 'LumiBased'
        #config.Data.splitting = 'FileBased'
	#config.Data.runRange = ''
	#config.Data.lumiMask  = ''
	#config.Data.unitsPerJob = 1

	config.Data.unitsPerJob = 20000

	#config.Data.totalUnits = 500000
        #config.Data.totalUnits = 3

        config.Data.outputDatasetTag = None
        #config.Data.outLFNDirBase = '/store/user/%s/mc_legacy_gen_'+era+'/' % (getUsernameFromSiteDB())
        config.Data.outLFNDirBase = '/store/user/%s/'% (getUsernameFromSiteDB()) + sampleType+'_legacy_gen_'+era+'/' 

        config.Site.storageSite = 'T3_US_FNALLPC' # Choose your site. 
        #--------------------------------------------------------

        # Will submit one task for each of these input datasets.
        inputDatasets = [

                            #'/SingleMuon/Run2016B-03Feb2017_ver2-v2/MINIAOD', 
                            #'/SingleMuon/Run2016C-03Feb2017-v1/MINIAOD',
                            #'/SingleMuon/Run2016D-03Feb2017-v1/MINIAOD',
                            #'/SingleMuon/Run2016E-03Feb2017-v1/MINIAOD',
                            #'/SingleMuon/Run2016F-03Feb2017-v1/MINIAOD',
                            #'/SingleMuon/Run2016G-03Feb2017-v1/MINIAOD',
                            #'/SingleMuon/Run2016H-03Feb2017_ver2-v1/MINIAOD',
                            #'/SingleMuon/Run2016H-03Feb2017_ver3-v1/MINIAOD',

                            #'/DoubleMuon/Run2016B-03Feb2017_ver2-v2/MINIAOD',
                            #'/DoubleMuon/Run2016C-03Feb2017-v1/MINIAOD',
                            #'/DoubleMuon/Run2016D-03Feb2017-v1/MINIAOD',
                            #'/DoubleMuon/Run2016E-03Feb2017-v1/MINIAOD',
                            #'/DoubleMuon/Run2016F-03Feb2017-v1/MINIAOD',
                            #'/DoubleMuon/Run2016G-03Feb2017-v1/MINIAOD',
                            #'/DoubleMuon/Run2016H-03Feb2017_ver2-v1/MINIAOD',
                            #'/DoubleMuon/Run2016H-03Feb2017_ver3-v1/MINIAOD',
                           
                            #'/DoubleEG/Run2016B-03Feb2017_ver2-v2/MINIAOD',
                            #'/DoubleEG/Run2016C-03Feb2017-v1/MINIAOD',
                            #'/DoubleEG/Run2016D-03Feb2017-v1/MINIAOD',
                            #'/DoubleEG/Run2016E-03Feb2017-v1/MINIAOD',
                            #'/DoubleEG/Run2016F-03Feb2017-v1/MINIAOD',
                            #'/DoubleEG/Run2016G-03Feb2017-v1/MINIAOD',
                            #'/DoubleEG/Run2016H-03Feb2017_ver2-v1/MINIAOD',
                            #'/DoubleEG/Run2016H-03Feb2017_ver3-v1/MINIAOD',

                            #'/MuOnia/Run2016B-03Feb2017_ver2-v2/MINIAOD',
                            #'/MuOnia/Run2016C-03Feb2017-v1/MINIAOD',
                            #'/MuOnia/Run2016D-03Feb2017-v1/MINIAOD',
                            #'/MuOnia/Run2016E-03Feb2017-v1/MINIAOD',
                            #'/MuOnia/Run2016F-03Feb2017-v1/MINIAOD',
                            #'/MuOnia/Run2016G-03Feb2017-v1/MINIAOD',
                            #'/MuOnia/Run2016H-03Feb2017_ver2-v1/MINIAOD',
                            #'/MuOnia/Run2016H-03Feb2017_ver3-v1/MINIAOD',
                            
                            #'/Charmonium/Run2016B-03Feb2017_ver2-v2/MINIAOD',
                            #'/Charmonium/Run2016C-03Feb2017-v1/MINIAOD',
                            #'/Charmonium/Run2016D-03Feb2017-v1/MINIAOD',
                            #'/Charmonium/Run2016E-03Feb2017-v1/MINIAOD',
                            #'/Charmonium/Run2016F-03Feb2017-v1/MINIAOD',
                            #'/Charmonium/Run2016G-03Feb2017-v1/MINIAOD',
                            #'/Charmonium/Run2016H-03Feb2017_ver2-v1/MINIAOD',
                            #'/Charmonium/Run2016H-03Feb2017_ver3-v1/MINIAOD',

			    ###############################
			    ########## RERECO #############

			    # '/ZGToLLG_01J_5f_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',
			    # '/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',
			    #'/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext2-v1/MINIAODSIM',

			    # #----- ZZ --------
			    # '/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',
			    # '/ZZTo2L2Nu_13TeV_powheg_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',
			    # '/ZZTo4L_13TeV_powheg_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',

			    # #----- WZ --------
			    # '/WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v3/MINIAODSIM',
			    # '/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',

			    # #----- WW --------
			    # '/WWToLNuQQ_13TeV-powheg/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',
			    # '/WWTo2L2Nu_13TeV-powheg/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',

			    # #----- TT --------
			    # '/TTTo2L2Nu_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',

			    # #----- WJets --------
			    # '/WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext2-v2/MINIAODSIM',

			    ######################################
			    ##########  2016 LEGACY  #############

			    ##------------------- Double Muon --------------
			    #'/DoubleMuon/Run2016B-17Jul2018_ver1-v1/MINIAOD',
			    #'/DoubleMuon/Run2016B-17Jul2018_ver2-v1/MINIAOD',
			    #'/DoubleMuon/Run2016C-17Jul2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2016D-17Jul2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2016E-17Jul2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2016F-17Jul2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2016G-17Jul2018-v1/MINIAOD',
			    #'/DoubleMuon/Run2016H-17Jul2018-v1/MINIAOD',
       
			    ##------------------ DoubleEG ------------------
			    #'/DoubleEG/Run2016B-17Jul2018_ver1-v1/MINIAOD',
			    #'/DoubleEG/Run2016B-17Jul2018_ver2-v1/MINIAOD',
			    #'/DoubleEG/Run2016C-17Jul2018-v1/MINIAOD',
			    #'/DoubleEG/Run2016D-17Jul2018-v1/MINIAOD',
			    #'/DoubleEG/Run2016E-17Jul2018-v1/MINIAOD',
			    #'/DoubleEG/Run2016F-17Jul2018-v1/MINIAOD',
			    #'/DoubleEG/Run2016G-17Jul2018-v1/MINIAOD',
			    #'/DoubleEG/Run2016H-17Jul2018-v1/MINIAOD',

			    ##-------------------  ZG & DYJets   --------------
			    #'/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext2-v1/MINIAODSIM',
			    #'/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext2-v2/MINIAODSIM',
			    #'/ZGToLLG_01J_5f_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v1/MINIAODSIM',


			    #'/WWTo2L2Nu_13TeV-powheg-herwigpp/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM',
			    #'/WWToLNuQQ_13TeV-powheg/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext1-v2/MINIAODSIM',


			    #'/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM',
			    #'/WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext1-v1/MINIAODSIM',

			    #'/ZZTo4L_13TeV-amcatnloFXFX-pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext1-v2/MINIAODSIM',
			    #'/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v1/MINIAODSIM',
			    #'/ZZTo2L2Nu_13TeV_powheg_pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM',

			    #'/TTTo2L2Nu_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM',
			    #'/WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext2-v1/MINIAODSIM',


			    ######################################
			    ##########  2017 LEGACY  #############

			    ##------------------- Double Muon --------------
			    '/DoubleMuon/Run2017B-31Mar2018-v1/MINIAOD',
			    '/DoubleMuon/Run2017C-31Mar2018-v1/MINIAOD',
			    '/DoubleMuon/Run2017D-31Mar2018-v1/MINIAOD',
			    '/DoubleMuon/Run2017E-31Mar2018-v1/MINIAOD',
			    '/DoubleMuon/Run2017F-31Mar2018-v1/MINIAOD',
 
			    ##------------------ DoubleEG ------------------
			    #'/DoubleEG/Run2017B-31Mar2018-v1/MINIAOD',
			    #'/DoubleEG/Run2017C-31Mar2018-v1/MINIAOD',
			    #'/DoubleEG/Run2017D-31Mar2018-v1/MINIAOD',
			    #'/DoubleEG/Run2017E-31Mar2018-v1/MINIAOD',
			    #'/DoubleEG/Run2017F-31Mar2018-v1/MINIAOD',

			    ##-------------------  ZG & DYJets   --------------
			    #'/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1/MINIAODSIM',
			    #'/ZGToLLG_01J_LoosePtlPtg_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/MINIAODSIM',

			    #'/WWTo2L2Nu_NNPDF31_TuneCP5Up_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/MINIAODSIM',

			    #'/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM',
			    #'/WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM',

			    #'/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM',
			    #'/ZZTo4L_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM',
			    #'/ZZTo2L2Nu_13TeV_powheg_pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM',

			    #'/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/MINIAODSIM',
			    #'/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v2/MINIAODSIM',
                        ]

        for inDS in inputDatasets:
            config.General.requestName = inDS.split('/')[1] + '_' + inDS.split('/')[2] 
	    config.General.requestName = config.General.requestName[:99]
            config.Data.inputDataset = inDS
            config.Data.outputDatasetTag = '%s_%s' % (config.General.workArea, config.General.requestName)
            # Submit.
            try:
                print "Submitting for input dataset %s" % (inDS)
                crabCommand(options.crabCmd, config = config, *options.crabCmdOpts.split())
            except HTTPException as hte:
                print "Submission for input dataset %s failed: %s" % (inDS, hte.headers)
            except ClientException as cle:
                print "Submission for input dataset %s failed: %s" % (inDS, cle)

    # All other commands can be simply executed.
    elif options.workArea:

        for dir in os.listdir(options.workArea):
            projDir = os.path.join(options.workArea, dir)
            if not os.path.isdir(projDir):
                continue
            # Execute the crab command.
            msg = "Executing (the equivalent of): crab %s --dir %s %s" % (options.crabCmd, projDir, options.crabCmdOpts)
            print "-"*len(msg)
            print msg
            print "-"*len(msg)
            try:
                crabCommand(options.crabCmd, dir = projDir, *options.crabCmdOpts.split())
            except HTTPException as hte:
                print "Failed executing command %s for task %s: %s" % (options.crabCmd, projDir, hte.headers)
            except ClientException as cle:
                print "Failed executing command %s for task %s: %s" % (options.crabCmd, projDir, cle)


if __name__ == '__main__':
    main()
